FROM openclassrooms/build_image

RUN apt-get update -yq \
&& apt-get install curl gnupg -yq \
&& curl -sL https://deb.nodesource.com/setup_10.x | bash \
&& apt-get install nginx -yq \
&& apt-get clean -y

